/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITokenASnapshot,
  ITokenASnapshotInterface,
} from "../../../contracts/interfaces/ITokenASnapshot";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "snapshotId",
        type: "uint256",
      },
    ],
    name: "balanceOfAt",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "snapshot",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITokenASnapshot__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenASnapshotInterface {
    return new Interface(_abi) as ITokenASnapshotInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITokenASnapshot {
    return new Contract(address, _abi, runner) as unknown as ITokenASnapshot;
  }
}
